---
title: "Hans-Hackathon"
author: Sebastian Sauer
date: today
toc: true
---

# Willkommen zum Projekt "Hans-Hackathon"!



Come to the HaNS-Side: we have [videos](https://www.youtube.com/watch?v=HAjXzW2v7OA).

## Gegenstand und Ziel

In diesem Modul analysieren Sie die Klickdaten zum KI-Tool [HaNS](https://www.th-nuernberg.de/einrichtungen-gesamt/in-institute/zentrum-fuer-kuenstliche-intelligenz-kiz/projekte/hans/).

Ziel ist es, das Tool HaNS zu evaluieren. Die Klickdaten sollen genutzt werden, um den Nutzen des Tools für die Studierenden besser einschätzen zu können. Darüber hinaus soll verstanden werden, wie Studierende das Tool zum Lernen nutzen, und wie das Tool verbessert werden kann, um das Lernen noch erfolgreicher zu gestalten.


## Kursaufbau und Didaktik 

Der grundlegende Aufbau ist, dass den Studierenden jede Woche eine "Challenge" ("Herausforderung", im Sinne eines Aufgabenpakets) präsentiert wird, die bis zur nächsten Woche gelöst werden soll.

Im Unterricht wird Material, das zur Lösung der Aufgabe nötig ist, besprochen oder es wird auf das Material verwiesen. 
In der folgenden Stunde stellt die Lehrkraft dann eine Musterlösung vor und bespricht die von den Studierenden eingereichte Lösung.
Dann wird wiederum eine neue Challenge angegangen usw.



    

## Modulverlauf 

Der [Modulverlauf](https://docs.google.com/spreadsheets/d/1hU9xIeeiEcOTCntSL7G-Gn2h4gkM4LAjVSId-uF9Fp4/edit?usp=sharing) gibt einen Überblick, welches Thema in welcher Woche bzw. wann behandelt wird. 
Pro Woche wird ein Thema behandelt.

:::{.callout-tip}
Es ist nützlich für Sie, den [Modulverlauf](https://docs.google.com/spreadsheets/d/1hU9xIeeiEcOTCntSL7G-Gn2h4gkM4LAjVSId-uF9Fp4/edit?usp=sharing) immer mal wieder zu konsultieren, damit sie wissen, welche Themen als nächstes behandelt werden. $\square$
:::



## Hinweise
Bitte beachten Sie, dass sich eine bestimmte Challenge noch ändern kann, solange sie nicht begonnen hat.
Beachten Sie auch die Prüfungshinweise und sonstige Hinweise im [Hinweisbuch](https://hinweisbuch.netlify.app/).


## Vorbereitung

Bitte stellen Sie sicher, dass Sie eine aktuelle Version von R auf Ihrem Computer am Laufen haben.
Bitte bringen Sie einen Computer (mit Internetanschluss) in jede Stunde mit.
Als Oberfläche (IDE) für R bietet sich neben RStudio auch die IDE von Posit an: [Positron](https://posit.co/products/ide/positron/).


## Werkzeuge

- [R](https://www.r-project.org/) (Programmiersprache)
- [RStudio](https://posit.co/download/rstudio-desktop/) (IDE für R)
- [Positron](https://posit.co/products/ide/positron/) (IDE für R, Alternative zu RStudio)
- [Quarto](https://quarto.org/) (für Berichte) - schon vorinstalliert in RStudio und Positron
- [Git](https://git-scm.com/) (Versionsverwaltung) - optiona
- [GitHub](https://www.github.com/) (Online-Plattform für Git-Repositories) - optional
- [Tidyverse](https://www.tidyverse.org/) (R-Paket-Sammlung für Datenanalyse)
- [Vim](https://www.vim.org/) (Texteditor) - optional; VIM-Modus in RStudio und Positron ist auch möglich; [Liebeserklärung an VIM](https://www.youtube.com/watch?v=sqm4-B07LsE)
- [Obsidian](https://obsidian.md/) (Notizen) - optional
- AI-Bots wie Claude, ChatGPT, Bard, etc. - optional, aber empfohlen

## Nutzen Sie KI-Dienste

Nutzen Sie KI-Dienste wie ChatGPT, Claude, Bard, etc., um Ihre Produktivität zu steigern.
Diese Dienste können Ihnen helfen, schneller zu programmieren, Fehler zu finden, Dokumentation zu verstehen, und vieles mehr.
Seien Sie kreativ und probieren Sie verschiedene Dienste aus, um herauszufinden, welcher Dienst am besten zu Ihnen passt.
IDEen wie RStudio und Positron haben oft auch Plugins oder Erweiterungen, die KI-Dienste integrieren.

## Los geht's!

Viel Erfolg und Spaß im Kurs!

